/**
 * Export Utilities for LifeLens AI / Norto
 * Supports Markdown export, styled PDF export via printable window, and .ics iCalendar file generation.
 */

export function exportToMarkdown(filename: string, content: string) {
  if (typeof window === 'undefined') return
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename.endsWith('.md') ? filename : `${filename}.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function exportToPDF(title: string, htmlBody: string) {
  if (typeof window === 'undefined') return
  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  const fullHTML = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <meta charset="utf-8" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
          body {
            font-family: 'Inter', system-ui, -apple-system, sans-serif;
            color: #1e293b;
            background: #ffffff;
            margin: 0;
            padding: 40px;
            line-height: 1.6;
          }
          .header {
            display: flex;
            align-items: center;
            justify-content: space-between;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 20px;
            margin-bottom: 30px;
          }
          .logo {
            font-size: 24px;
            font-weight: 800;
            color: #dd0200;
            display: flex;
            align-items: center;
            gap: 8px;
          }
          .title {
            font-size: 22px;
            font-weight: 700;
            color: #0f172a;
            margin-top: 0;
          }
          .date {
            font-size: 12px;
            color: #64748b;
          }
          .content {
            font-size: 14px;
          }
          h1, h2, h3 { color: #0f172a; margin-top: 1.5em; margin-bottom: 0.5em; }
          h1 { font-size: 20px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }
          h2 { font-size: 16px; }
          h3 { font-size: 14px; }
          ul, ol { padding-left: 20px; }
          li { margin-bottom: 6px; }
          .footer {
            margin-top: 40px;
            border-top: 1px solid #e2e8f0;
            padding-top: 16px;
            font-size: 11px;
            color: #94a3b8;
            text-align: center;
          }
          @media print {
            body { padding: 0; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">
            <span>🌿 Norto AI</span>
          </div>
          <div class="date">Generated on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</div>
        </div>
        <h1 class="title">${title}</h1>
        <div class="content">
          ${htmlBody}
        </div>
        <div class="footer">
          Generated by Norto — Your AI Companion for Every New City · https://norto.ai
        </div>
        <script>
          window.onload = function() {
            setTimeout(function() {
              window.print();
            }, 300);
          };
        </script>
      </body>
    </html>
  `

  printWindow.document.write(fullHTML)
  printWindow.document.close()
}

export interface ICSEvent {
  title: string
  description: string
  startDate?: Date
  location?: string
}

export function generateAndDownloadICS(filename: string, events: ICSEvent[]) {
  if (typeof window === 'undefined' || events.length === 0) return

  const formatDate = (date: Date) => {
    return date.toISOString().replace(/-|:|\.\d+/g, '').slice(0, 15) + 'Z'
  }

  const now = formatDate(new Date())

  let icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Norto AI//Relocation Companion//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
  ].join('\r\n') + '\r\n'

  events.forEach((evt, idx) => {
    const start = evt.startDate || new Date(Date.now() + (idx + 1) * 86400000)
    const end = new Date(start.getTime() + 3600000) // 1 hour duration

    icsContent += [
      'BEGIN:VEVENT',
      `UID:norto-${Date.now()}-${idx}@norto.ai`,
      `DTSTAMP:${now}`,
      `DTSTART:${formatDate(start)}`,
      `DTEND:${formatDate(end)}`,
      `SUMMARY:${evt.title.replace(/\n/g, ' ')}`,
      `DESCRIPTION:${evt.description.replace(/\n/g, '\\n')}`,
      evt.location ? `LOCATION:${evt.location.replace(/\n/g, ' ')}` : '',
      'STATUS:CONFIRMED',
      'END:VEVENT',
    ].filter(Boolean).join('\r\n') + '\r\n'
  })

  icsContent += 'END:VCALENDAR'

  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename.endsWith('.ics') ? filename : `${filename}.ics`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
